"""create initial tables

Revision ID: 01e0b215eefb
Revises: 
Create Date: 2025-06-05 11:00:56.863212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e0b215eefb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('card', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('driver_full_name', sa.String(), nullable=True),
    sa.Column('request_pin', sa.Boolean(), nullable=True),
    sa.Column('request_vehicle_id', sa.Boolean(), nullable=True),
    sa.Column('pin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('card')
    )
    op.create_index(op.f('ix_drivers_card'), 'drivers', ['card'], unique=False)
    op.create_table('erogations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('driver_full_name', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('company_vehicle', sa.String(), nullable=True),
    sa.Column('vehicle_total_km', sa.String(), nullable=True),
    sa.Column('erogation_side', sa.Integer(), nullable=False),
    sa.Column('dispensed_liters', sa.Float(), nullable=True),
    sa.Column('dispensed_product', sa.String(), nullable=True),
    sa.Column('erogation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('total_erogation_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('totals',
    sa.Column('dispenser_id', sa.Integer(), nullable=False),
    sa.Column('total_side_1', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_side_2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('dispenser_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('company_vehicle', sa.String(), nullable=True),
    sa.Column('request_vehicle_km', sa.Boolean(), nullable=True),
    sa.Column('vehicle_total_km', sa.String(), nullable=True),
    sa.Column('plate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('plate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('totals')
    op.drop_table('erogations')
    op.drop_index(op.f('ix_drivers_card'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
